const fs = require('fs');
const path = require('path');

/**
 * Generate a comprehensive Cursor AI prompt from the analysis results
 * This command creates a ready-to-copy prompt for Cursor AI based on the 
 * rich context generated by the ai-fix command
 */
async function generateCursorPrompt(options = {}) {
    const contextFile = path.join(process.cwd(), '.cursor-ai-fix-request.json');
    
    // Check if analysis file exists
    if (!fs.existsSync(contextFile)) {
        console.error('❌ No analysis file found!');
        console.log('💡 Run "jira ai-fix ISSUE-KEY" first to generate the analysis.');
        return;
    }

    try {
        const context = JSON.parse(fs.readFileSync(contextFile, 'utf8'));
        
        console.log('🚀 Generating Cursor AI prompt...\n');
        
        // Generate the prompt
        const prompt = buildCursorAIPrompt(context, options);
        
        // Output options
        if (options.copy) {
            // Copy to clipboard if requested (would need a clipboard library)
            console.log('📋 Prompt copied to clipboard!');
        }
        
        if (options.save) {
            // Save to file
            const promptFile = path.join(process.cwd(), 'cursor-prompt.md');
            fs.writeFileSync(promptFile, prompt);
            console.log(`💾 Prompt saved to: ${promptFile}`);
        }
        
        // Always display the prompt
        console.log('=' .repeat(80));
        console.log('🎯 CURSOR AI PROMPT (Ready to Copy & Paste)');
        console.log('=' .repeat(80));
        console.log(prompt);
        console.log('=' .repeat(80));
        
        // Usage instructions
        console.log('\n📝 Usage Instructions:');
        console.log('1. Copy the above prompt');
        console.log('2. Open Cursor AI chat');
        console.log('3. Paste and send the prompt');
        console.log('4. Cursor AI will have full context including attachments');
        
        if (context.attachments?.hasAttachments) {
            console.log(`\n📎 Attachments available in: .jira-attachments/`);
            context.attachments.analysis.forEach(att => {
                if (att.localPath) {
                    console.log(`   • ${att.filename} → ${att.localPath}`);
                }
            });
        }
        
    } catch (error) {
        console.error('❌ Error reading analysis file:', error.message);
        console.log('💡 Make sure the .cursor-ai-fix-request.json file is valid JSON.');
    }
}

/**
 * Build a comprehensive Cursor AI prompt
 */
function buildCursorAIPrompt(context, options = {}) {
    const { issueKey, summary, description, attachments, contextualInsights, suggestedCodeAreas, searchStrategy } = context;
    
    let prompt = `# 🎯 JIRA Issue Resolution Request

## 📋 Issue Information
- **Issue Key**: ${issueKey}
- **Summary**: ${summary}
- **Status**: ${context.status}
- **Priority**: ${context.priority}
- **Type**: ${contextualInsights?.issueType || 'General Issue'}
- **Complexity**: ${contextualInsights?.complexity || 'Medium'}

## 📝 Description
${description}`;

    // Add attachment context
    if (attachments?.hasAttachments) {
        prompt += `

## 📎 Visual Context & Attachments
I have ${attachments.count} attachment(s) that provide important context:

### 🖼️ Visual Evidence`;

        attachments.analysis.forEach((att, index) => {
            prompt += `

**${index + 1}. ${att.filename}**`;
            
            if (att.localPath) {
                prompt += `
- **File Path**: \`${att.localPath}\``;
            }
            
            if (att.contentAnalysis?.type === 'image') {
                prompt += `
- **Type**: ${att.contentAnalysis.isScreenshot ? 'Screenshot' : 'Image'}`;
                
                if (att.contentAnalysis.dimensions) {
                    prompt += `
- **Size**: ${att.contentAnalysis.dimensions.width}x${att.contentAnalysis.dimensions.height}px`;
                }
                
                if (att.contentAnalysis.extractedElements?.length > 0) {
                    prompt += `
- **UI Components**: ${att.contentAnalysis.extractedElements.join(', ')}`;
                }
                
                if (att.contentAnalysis.suggestedContext?.length > 0) {
                    prompt += `
- **Context**: ${att.contentAnalysis.suggestedContext.join(', ')}`;
                }
                
                if (att.contentAnalysis.isErrorState) {
                    prompt += `
- **⚠️ Error State**: This image shows an error or problematic state`;
                }
            } else if (att.contentAnalysis?.type === 'code') {
                prompt += `
- **Type**: Code file (${att.contentAnalysis.language})
- **Lines**: ${att.contentAnalysis.lineCount}
- **Complexity**: ${att.contentAnalysis.complexity?.level}`;
            } else if (att.contentAnalysis?.hasErrorLogs) {
                prompt += `
- **Type**: Error log file
- **Contains**: Stack traces and error information`;
            }
            
            if (att.downloadError) {
                prompt += `
- **Note**: File analysis limited due to access restrictions`;
            }
        });

        if (attachments.summary?.keyFindings?.length > 0) {
            prompt += `

### 🔍 Key Findings
${attachments.summary.keyFindings.map(finding => `- ${finding}`).join('\n')}`;
        }
    }

    // Add investigation strategy
    if (suggestedCodeAreas?.length > 0 || searchStrategy?.primarySearchTerms?.length > 0) {
        prompt += `

## 🎯 Investigation Strategy`;

        if (suggestedCodeAreas?.length > 0) {
            prompt += `

### 🔍 Focus Areas
${suggestedCodeAreas.slice(0, 6).map(area => `- ${area}`).join('\n')}`;
        }

        if (searchStrategy?.primarySearchTerms?.length > 0) {
            prompt += `

### 🔎 Search Terms
${searchStrategy.primarySearchTerms.slice(0, 8).map(term => `- \`${term}\``).join('\n')}`;
        }
    }

    // Add technical context
    if (contextualInsights?.technicalClues?.length > 0 || contextualInsights?.visualContext?.length > 0) {
        prompt += `

## 🔧 Technical Context`;

        if (contextualInsights.technicalClues?.length > 0) {
            prompt += `

### 💡 Technical Clues
${contextualInsights.technicalClues.map(clue => `- ${clue}`).join('\n')}`;
        }

        if (contextualInsights.visualContext?.length > 0) {
            prompt += `

### 👁️ Visual Context
${contextualInsights.visualContext.map(context => `- ${context}`).join('\n')}`;
        }
    }

    // Add specific instructions based on issue type
    prompt += `

## 🤖 Request

Please help me resolve this JIRA issue by:

1. **📁 Analyzing the attachments** in the \`.jira-attachments/\` folder to understand the visual context`;

    if (attachments?.hasAttachments && attachments.summary?.imageCount > 0) {
        prompt += `
2. **🖼️ Examining the screenshots** to understand exactly what needs to be fixed`;
    }

    prompt += `
3. **🔍 Searching the codebase** using the suggested terms and focus areas above
4. **🛠️ Implementing the solution** that addresses the specific issue shown in the attachments
5. **✅ Testing the changes** to ensure they work correctly`;

    // Add issue-specific guidance
    switch (contextualInsights?.issueType) {
        case 'UI/UX Issue':
        case 'Visual Bug':
        case 'Component Issue':
            prompt += `

### 🎨 UI/Component Focus
- Pay special attention to the visual elements shown in the screenshots
- Check for CSS/styling issues, component rendering problems, or layout issues
- Ensure the fix addresses the exact visual problem demonstrated`;
            break;
            
        case 'Runtime Error':
            prompt += `

### 🐛 Error Resolution Focus
- Analyze any error logs or stack traces in the attachments
- Trace the error back to its root cause in the codebase
- Implement proper error handling and validation`;
            break;
            
        case 'Feature Implementation':
            prompt += `

### ⚡ Feature Implementation Focus
- Understand the requirements from the description and visual context
- Follow existing code patterns and architecture
- Ensure the new feature integrates seamlessly`;
            break;
    }

    prompt += `

## 📋 Additional Context

- **Repository**: ${context.repoPath}
- **Analysis Date**: ${context.timestamp}
- **Local Attachments**: Available in \`.jira-attachments/\` folder`;

    if (attachments?.hasAttachments) {
        prompt += `
- **Visual Evidence**: ${attachments.count} file(s) provide context for this issue`;
    }

    prompt += `

---

**Please proceed with the analysis and implementation. I have provided all the necessary context including visual evidence from the JIRA attachments.**`;

    return prompt;
}

/**
 * Generate a simple prompt for quick fixes
 */
function buildSimplePrompt(context) {
    return `# Fix JIRA Issue: ${context.issueKey}

**Summary**: ${context.summary}

**Description**: ${context.description || 'No description provided'}

**Request**: Please analyze the codebase and implement a solution for this JIRA issue.

${context.attachments?.hasAttachments ? 
    `**Note**: Visual context available in .jira-attachments/ folder` : 
    ''}`;
}

module.exports = { generateCursorPrompt };